# Site settings
title: Andrew Tran
description: "Projects, Works in Progress, Achievements"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Andrew Tran"
resume_title:                   "Software Engineer"
resume_contact_email:
  "avtran23@gmail.com"
resume_header_contact_info: "(626) 272 - 8170 | avtran23@gmail.com"
resume_header_intro: "<p>Full-Stack Software Engineer, with a passion for projects that shape cultures, shake paradigms, and empower the individual. I seek innovation with which to rejuvenate stagnation, and elegant solutions that withstand time and change. Though software design is my craft, my true medium is ideas.

Reach me at avtran23@gmail.com, and view my projects at https://github.com/LeatherGreenGargoyle.

Skills: Javascript, HTML5, NodeJS, Angular, Angular 2, React, React-Native, Redux, Angular Material, MySQL, Sequelize, ExpressJS, Passport, Auth0 Bluebird, CSS3, Backbone, Typescript, Mocha, Chai, MongoDB, Mongoose</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
